<div class="default-portfolio-item mix mix_all portfolio col-lg-3 col-md-4 col-sm-6 col-xs-12 [field:typename/]">
	                    <div class="inner-box">
	                        <figure class="image"><img src="[field:litpic/]" alt="[field:fulltitle/]" height="290" ></figure>
	                        <div class="overlay-box">
	                        	<div class="content-box">
	                                <div class="content">
	                                	<h2 style=" font-size:18px;"><a href="[field:keywords/]">[field:title/]</a></h2>
	                                </div>
	                            </div>
	                            <span class="line-left"></span><span class="line-bottom"></span><span class="line-right"></span><span class="line-top"></span>
	                        </div>
	                    </div>
	                </div>