<div class="pricing-table col-md-3 col-sm-6 col-xs-12">
	                	<div class="inner-box wow fadeIn" data-wow-delay="900ms" data-wow-duration="1500ms">
	                    	<div class="table-header">
	                    		<h3 class="price">[field:title/]</h3>
	                            <div class="icon-right"><span class="flaticon-medal"></span></div>
	                        </div>
	                        
	                        <div style=" width:270px; height:180px;">
	                        	<img src="[field:litpic/]" style=" width:250px; height:160px; margin-left:9px; margin-top:10px;">
	                        </div>
	                        <div class="table-footer" style=" height:180px; ">
	                        	[field:description/]
	                        </div>
	                        
	                    </div>
	                </div>