<a href="[field:description/]" target="_blank">
		 <div class="[field:typename/] default-portfolio-item" style=" width:305px; height:220px;  float:left; margin:15px 15px;">
	                    <div class="inner-box">
	                        <figure class="image"><img src="[field:litpic/]" alt="[field:shorttitle/]" height="220" ></figure>
	                        <div class="overlay-box">
	                        	<div class="content-box">
	                                <div class="content">
	                                	<h2 style=" font-size:18px; color:white;">[field:title/]</h2>
	                                </div>
	                            </div>
	                            <span class="line-left"></span><span class="line-bottom"></span><span class="line-right"></span><span class="line-top"></span>
	                        </div>
	                    </div>
	                </div>
		 </a>