<?php
$z[0]=Array("sql","          \r\n                            	<figure class=\"image\"><a href=\"[field:description/]\" target=\"_blank\" class=\"lightbox-image\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" height=\"70\"></a></figure>    \r\n                            ",2862,3255);
$z[0][4]=array();
$z[0][4]['sql']="Select id,title,litpic,description from dede_archives where typeid=14 order by senddate desc limit 0,6";

?>