<?php
$z[0]=Array("global","",80,105);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n        <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n        ",146,391);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[2]=Array("global","",1016,1041);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\r\n                            <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n                            ",1102,1387);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>