<?php
$z[0]=Array("global","",955,980);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\n			<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\n			",1015,1248);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[2]=Array("global","",1717,1742);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\n								<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\n								",1782,2025);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[4]=Array("global","",4191,4216);
$z[4][4]=array();
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\n							<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\n							",4255,4496);
$z[5][4]=array();
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[6]=Array("global","",4629,4655);
$z[6][4]=array();
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",4719,4743);
$z[7][4]=array();
$z[7][4]['name']="cfg_beian";

?>